runtime: python39
entrypoint: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0

env_variables:
  BACKEND_URL: "https://newsletter-backend-162421115459.us-central1.run.app"  # Replace with your actual Cloud Run service URL
  STREAMLIT_SERVER_PORT: "$PORT"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto
  secure: always